"""
insert_MT_restyled_DMSO_vs_Noco_slides.py

MT (microtubule) geom-density deck built from the RESTYLED figures (DMSO blue vs
Noco 1 μM orange, sig stars, single Perinuclear panel — MT is cytoplasmic).
Leads with the curated publication-clean set (MT_loc_wrto_invag: 02 density /
03 enrichment / 04 correlation), plus the centrosome-PROXIMAL enrichment
(near_cent) — the live half of the new proximal/distal split. The full
proximal + distal enrichment/correlation split is still being generated by the
MATLAB pipeline and will be wired in when it lands.

Usage:
    conda run -n PPT_editing python examples_and_configs/insert_MT_restyled_DMSO_vs_Noco_slides.py
    conda run -n PPT_editing python examples_and_configs/insert_MT_restyled_DMSO_vs_Noco_slides.py --list
"""

import math
import os
import sys
from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt

try:
    from PIL import Image
except ImportError:  # pragma: no cover
    Image = None

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ppt_image_inserter import backup_presentation, safe_path, path_exists  # noqa: E402

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
RESTYLED = Path(
    "M:/FF/FF_4TB_2_Backup_fullHD/Nucleus Project_2ndharddrive/"
    "prog_fixed_Noco_MT_20240123/results_compilation_MT_geomdensity_20260718/"
    "restyled")
CURATED = RESTYLED / "MT_loc_wrto_invag"
NC = RESTYLED / "geom_density" / "near_cent"
ENR = RESTYLED / "geom_density" / "enrichment"
BYCENT = RESTYLED / "geom_density" / "profiles" / "bycent"
INDIV = RESTYLED / "individual_plots" / "Jan_23,_2024"

OUTPUT_PATH = Path(
    "K:/FF/PPT/PPT_autogeneration/Fixed Jurkats, Miscellaneous/"
    "nuc_mesh_struct_outside_nuc/"
    "MT geom-density vs NE geometry, DMSO vs Noco (restyled, 20260722).pptx")

DECK_TITLE = "Microtubules vs nuclear-envelope geometry — DMSO vs Noco (restyled)"
DECK_SUBTITLE = (
    "Fixed Jurkats · Nocodazole (Jan 23 2024) · DMSO (blue, n=77) vs "
    "Noco 1 μM (orange, n=43) · MT = perinuclear (cytoplasmic) · "
    "curated restyled figures · 2026-07-22")

FOOTER_CMP = "DMSO (blue) vs Noco 1 μM (orange)"

# ---------------------------------------------------------------------------
# Colors / layout (16:9)
# ---------------------------------------------------------------------------
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
BLACK = RGBColor(0x00, 0x00, 0x00)
GREY = RGBColor(0x55, 0x55, 0x55)
FIELD_COLOR = RGBColor(0x2E, 0x5A, 0x88)
DIVIDER_BG = RGBColor(0xF0, 0xF0, 0xF0)

SLIDE_W = 13.333
SLIDE_H = 7.5
MARGIN = 0.08
GAP = 0.10

TITLE_LEFT = MARGIN
TITLE_TOP = 0.04
TITLE_WIDTH = SLIDE_W - 2 * MARGIN
TITLE_HEIGHT = 0.50
TITLE_FONT_PT = 27

IMG_TOP = 0.58
FOOTER_TOP = 7.20
FOOTER_WIDTH = SLIDE_W - 2 * MARGIN
FOOTER_HEIGHT = 0.28
FOOTER_FONT_PT = 8
MAX_GRID_COLS = 5


# ---------------------------------------------------------------------------
# Slide helpers
# ---------------------------------------------------------------------------
def add_textbox(slide, text, left, top, width, height, font_pt, color,
                bold=False, italic=False, align=PP_ALIGN.CENTER, wrap=True):
    box = slide.shapes.add_textbox(
        Inches(left), Inches(top), Inches(width), Inches(height))
    tf = box.text_frame
    tf.word_wrap = wrap
    tf.margin_left = Inches(0.05)
    tf.margin_right = Inches(0.05)
    tf.margin_top = Inches(0.02)
    tf.margin_bottom = Inches(0.02)
    tf.text = text
    para = tf.paragraphs[0]
    para.alignment = align
    run = para.runs[0]
    run.font.size = Pt(font_pt)
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = color
    return box


def title_font_for(text):
    n = len(text)
    if n <= 52:
        return TITLE_FONT_PT
    if n <= 70:
        return 24
    if n <= 90:
        return 20
    return 18


def add_image_in_box(slide, image_path, box_left, box_top, box_w, box_h):
    image_path = safe_path(image_path)
    pic = slide.shapes.add_picture(
        image_path, Inches(box_left), Inches(box_top), width=Inches(box_w))
    actual_h_in = pic.height / 914400.0
    if actual_h_in > box_h:
        sp = pic._element
        sp.getparent().remove(sp)
        pic = slide.shapes.add_picture(
            image_path, Inches(box_left), Inches(box_top), height=Inches(box_h))
        actual_w_in = pic.width / 914400.0
        pic.left = Inches(box_left + (box_w - actual_w_in) / 2)
    else:
        pic.top = Inches(box_top + (box_h - actual_h_in) / 2)
    return pic


def set_slide_background(slide, rgb):
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = rgb


def _new_slide(prs, bg=WHITE):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    set_slide_background(slide, bg)
    return slide


def build_title_slide(prs, title, subtitle):
    slide = _new_slide(prs)
    add_textbox(slide, title, MARGIN, 2.6, SLIDE_W - 2 * MARGIN, 1.3,
                font_pt=32, color=BLACK, bold=True)
    add_textbox(slide, subtitle, MARGIN, 4.0, SLIDE_W - 2 * MARGIN, 1.3,
                font_pt=15, color=GREY, italic=True)


def build_divider_slide(prs, title, subtitle=""):
    slide = _new_slide(prs, bg=DIVIDER_BG)
    add_textbox(slide, title, MARGIN, 3.0, SLIDE_W - 2 * MARGIN, 1.2,
                font_pt=36, color=BLACK, bold=True)
    if subtitle:
        add_textbox(slide, subtitle, MARGIN, 4.25, SLIDE_W - 2 * MARGIN, 0.9,
                    font_pt=18, color=GREY, italic=True)


def add_labeled_caption(slide, lines, left, top, width, height):
    box = slide.shapes.add_textbox(
        Inches(left), Inches(top), Inches(width), Inches(height))
    tf = box.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0.03)
    tf.margin_right = Inches(0.03)
    tf.margin_top = Inches(0.0)
    tf.margin_bottom = Inches(0.0)
    for i, (text, pt, color) in enumerate(lines):
        para = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        para.alignment = PP_ALIGN.CENTER
        run = para.add_run()
        run.text = text
        run.font.size = Pt(pt)
        run.font.color.rgb = color
    return box


def _tile_caption(slide, cap, path, left, top, width, height, cap_pt):
    lines = []
    if cap:
        lines.append((cap, min(cap_pt, 11), GREY))
    lines.append((Path(str(path)).stem, 8, FIELD_COLOR))
    add_labeled_caption(slide, lines, left, top, width, height)


_AR_CACHE = {}


def _img_ar(path):
    key = str(path)
    if key in _AR_CACHE:
        return _AR_CACHE[key]
    ar = 1.5
    if Image is not None:
        try:
            with Image.open(safe_path(key)) as im:
                w, h = im.size
                if h:
                    ar = w / float(h)
        except Exception:
            pass
    _AR_CACHE[key] = ar
    return ar


def _uniform_img_size(a, cols, rows, area_w, area_h, cap_h):
    cw = (area_w - (cols - 1) * GAP) / cols
    cell_h = (area_h - (rows - 1) * GAP) / rows
    ih_avail = cell_h - cap_h
    if ih_avail <= 0.2 or cw <= 0.2:
        return None
    iw = min(cw, ih_avail * a)
    return iw, iw / a


def _best_cols(ars, n, area_w, area_h, cap_h, cap_cols):
    uniform = (max(ars) / min(ars)) < 1.20
    a = sorted(ars)[len(ars) // 2]
    best = None
    for cols in range(1, min(cap_cols, n) + 1):
        rows = math.ceil(n / cols)
        if uniform:
            sz = _uniform_img_size(a, cols, rows, area_w, area_h, cap_h)
            if sz is None:
                continue
            score = sz[0] * sz[1]
        else:
            cw = (area_w - (cols - 1) * GAP) / cols
            cell_h = (area_h - (rows - 1) * GAP) / rows
            ih_avail = cell_h - cap_h
            if ih_avail <= 0.2 or cw <= 0.2:
                continue
            score = 0.0
            for ai in ars:
                iw = min(cw, ih_avail * ai)
                score += iw * (iw / ai)
        if best is None or score > best[0] + 1e-6:
            best = (score, cols, rows, uniform)
    if best is None:
        c = min(cap_cols, n)
        return c, math.ceil(n / c), uniform
    return best[1], best[2], best[3]


def build_grid_slide(prs, title, entries, footer_text, cap_pt=11, cap_h=0.34):
    slide = _new_slide(prs)
    add_textbox(slide, title, TITLE_LEFT, TITLE_TOP, TITLE_WIDTH, TITLE_HEIGHT,
                font_pt=title_font_for(title), color=BLACK, bold=True)
    n = len(entries)
    area_top = IMG_TOP
    area_w = SLIDE_W - 2 * MARGIN
    area_h = FOOTER_TOP - IMG_TOP - 0.02

    ars = [_img_ar(p) for p, _ in entries]
    cols, rows, uniform = _best_cols(ars, n, area_w, area_h, cap_h,
                                     min(MAX_GRID_COLS, n))
    if uniform:
        a = sorted(ars)[len(ars) // 2]
        iw, ih = _uniform_img_size(a, cols, rows, area_w, area_h, cap_h)
        block_w = cols * iw + (cols - 1) * GAP
        block_h = rows * (ih + cap_h) + (rows - 1) * GAP
        x0 = MARGIN + (area_w - block_w) / 2
        y0 = area_top + max(0.0, (area_h - block_h) / 2)
        for i, (path, cap) in enumerate(entries):
            r, c = divmod(i, cols)
            left = x0 + c * (iw + GAP)
            top = y0 + r * (ih + cap_h + GAP)
            add_image_in_box(slide, str(path), left, top, iw, ih)
            _tile_caption(slide, cap, path, left, top + ih, iw, cap_h, cap_pt)
    else:
        cell_w = (area_w - (cols - 1) * GAP) / cols
        cell_h = (area_h - (rows - 1) * GAP) / rows
        img_h = cell_h - cap_h
        for i, (path, cap) in enumerate(entries):
            r, c = divmod(i, cols)
            left = MARGIN + c * (cell_w + GAP)
            top = area_top + r * (cell_h + GAP)
            add_image_in_box(slide, str(path), left, top, cell_w, img_h)
            _tile_caption(slide, cap, path, left, top + img_h,
                          cell_w, cap_h, cap_pt)

    add_textbox(slide, footer_text, MARGIN, FOOTER_TOP, FOOTER_WIDTH,
                FOOTER_HEIGHT, font_pt=FOOTER_FONT_PT, color=GREY)
    return slide


# ---------------------------------------------------------------------------
# Content plan
# ---------------------------------------------------------------------------
def build_plan():
    plan, missing = [], []

    def add_grid(title, pairs, footer=FOOTER_CMP):
        kept, miss = [], []
        for path, cap in pairs:
            (kept if path_exists(path) else miss).append((path, cap))
        missing.extend(p for p, _ in miss)
        if kept:
            plan.append(("grid", title, kept, footer))

    # --- Sec 1: density vs geometry (curated 02a-c, Mean±SEM line) ---
    plan.append(("divider", "MT density vs NE geometry",
                 "area-weighted density vs shape · " + FOOTER_CMP))
    add_grid("MT density vs NE geometry (Mean ± SEM)",
             [(CURATED / "02a_MT_avg_hulldist.png", "vs hull-boundary distance"),
              (CURATED / "02b_MT_avg_minCurvature_concave.png",
               "vs min curvature (concave)"),
              (CURATED / "02c_MT_avg_meanCurvature_concave.png",
               "vs mean curvature (concave)")])

    # --- Sec 2: per-cell enrichment (curated 03a-e) ---
    plan.append(("divider", "MT per-cell enrichment in invaginations & concave NE",
                 "region density ÷ cell mean (>1 = enriched) · one dot per cell"))
    add_grid("MT enrichment in deep invaginations (hull-boundary distance)",
             [(CURATED / "03a_MT_enrichment_hulldist_gt0.5um.png", "dist > 0.5 μm"),
              (CURATED / "03b_MT_enrichment_hulldist_gt1.0um.png", "dist > 1.0 μm")],
             "region density ÷ cell mean · ref line 1 · " + FOOTER_CMP)
    add_grid("MT enrichment on concave NE (headline: min curv < 0)",
             [(CURATED / "03c_MT_enrichment_minCurvature_lt0.png",
               "min curv < 0  (headline)"),
              (CURATED / "03d_MT_enrichment_minCurvature_ltm0.25.png",
               "min curv < −0.25"),
              (CURATED / "03e_MT_enrichment_meanCurvature.png",
               "mean curv < 0")],
             "region density ÷ cell mean · ref line 1 · " + FOOTER_CMP)

    # --- Sec 3: per-cell correlation (curated 04a-c) ---
    plan.append(("divider", "MT per-cell correlation vs NE geometry",
                 "per-cell area-weighted Pearson r · one dot per cell · "
                 "ref line 0"))
    add_grid("MT correlation vs NE geometry (per-cell Pearson r)",
             [(CURATED / "04a_MT_correlation_hulldist.png", "vs hull distance"),
              (CURATED / "04b_MT_correlation_minCurvature.png",
               "vs min curvature"),
              (CURATED / "04c_MT_correlation_meanCurvature.png",
               "vs mean curvature")],
             "ref line 0 · " + FOOTER_CMP)

    # --- Sec 4: centrosome PROXIMAL vs DISTAL breakdown (the new result) ---
    plan.append((
        "divider", "Centrosome proximal vs distal — the new result",
        "near the centrosome MT favors concave faces (strongly in Noco); "
        "distally that inverts — Noco becomes depleted on concave / "
        "enriched on convex"))

    # The clean summary: proximal ÷ distal ratio (one violin)
    add_grid("MT proximal ÷ distal ratio — per-cell summary",
             [(NC / "MT_near_cent_prox_over_distal_ratio_pooled.png",
               "perinuclear MT density: near-cent ÷ away-cent")],
             "ref line 1 = no bias · DMSO median ~1.58, Noco ~1.89 (**) · "
             + FOOTER_CMP)

    # Each breakdown is ONE 1×2 figure: Proximal | Distal (shared y-axis).
    add_grid("MT enrichment on concave NE (min curv < 0) — proximal | distal",
             [(ENR / "MT_mincurv_lt0_shells_bycent_pooled.png", None)],
             "headline · region density ÷ cell mean · ref line 1 · " + FOOTER_CMP)
    add_grid("MT enrichment in deep invaginations (hull dist > 0.5 μm) — "
             "proximal | distal",
             [(ENR / "MT_hulldist_gt0.5um_shells_bycent_pooled.png", None)],
             "region density ÷ cell mean · ref line 1 · " + FOOTER_CMP)
    add_grid("MT correlation vs min curvature — proximal | distal",
             [(ENR / "MT_corr_mincurv_shells_bycent_pooled.png", None)],
             "per-cell Pearson r · ref line 0 · " + FOOTER_CMP)
    add_grid("MT correlation vs hull-boundary distance — proximal | distal",
             [(ENR / "MT_corr_hulldist_shells_bycent_pooled.png", None)],
             "per-cell Pearson r · ref line 0 · " + FOOTER_CMP)
    add_grid("MT density vs hull-boundary distance — proximal | distal",
             [(BYCENT / "MT_geomdens_hulldist_shells_OVERLAY_line_bycent_pooled.png",
               None)],
             "Mean ± SEM density vs distance inside the hull · " + FOOTER_CMP)
    add_grid("MT density vs min curvature — proximal | distal",
             [(BYCENT / "MT_geomdens_mincurv_shells_OVERLAY_line_bycent_pooled.png",
               None)],
             "Mean ± SEM density vs curvature · " + FOOTER_CMP)
    add_grid("MT density vs mean curvature — proximal | distal",
             [(BYCENT / "MT_geomdens_meancurv_shells_OVERLAY_line_bycent_pooled.png",
               None)],
             "Mean ± SEM density vs curvature · " + FOOTER_CMP)

    # --- Sec 5: invagination-pocket scalars (individual_plots) ---
    plan.append(("divider", "MT in nuclear invagination pockets",
                 "voxel convex-hull decomposition · " + FOOTER_CMP))
    add_grid("MT in nuclear invagination pockets",
             [(INDIV / "MT_cyto_in_nuc_hull_vs_near_convex_nuc_MFI_ratio.png",
               "grooves ÷ convex surface"),
              (INDIV / "MT_cyto_in_nuc_hull_vs_nuc_MFI_ratio.png",
               "grooves ÷ nucleus MFI"),
              (INDIV / "MT_cyto_in_nuc_hull_vs_all_perinuc_MFI_ratio.png",
               "grooves ÷ whole perinuc"),
              (INDIV / "MT_cyto_in_nuc_hull_MFI.png", "grooves MFI"),
              (INDIV / "MT_cyto_in_nuc_hull_sig_fraction.png",
               "fraction of signal in grooves")],
             "ref line 1 · " + FOOTER_CMP)

    # --- Drop orphan dividers ---
    cleaned = []
    for i, it in enumerate(plan):
        if it[0] == "divider":
            if i + 1 >= len(plan) or plan[i + 1][0] == "divider":
                continue
        cleaned.append(it)
    return cleaned, missing


def main():
    list_only = "--list" in sys.argv
    plan, missing = build_plan()

    print("Output: {}".format(OUTPUT_PATH))
    print("{} content slides (+ title) = {} total\n".format(
        len(plan), 1 + len(plan)))
    for it in plan:
        if it[0] == "divider":
            print("\n=== {} ===".format(it[1]))
        else:
            print("  [{}] {}".format(len(it[2]), it[1]))
    if missing:
        print("\nMISSING ({}):".format(len(missing)))
        for m in missing:
            print("  - {}".format(m))
    if list_only:
        return

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    prs = Presentation()
    prs.slide_width = Inches(SLIDE_W)
    prs.slide_height = Inches(SLIDE_H)
    build_title_slide(prs, DECK_TITLE, DECK_SUBTITLE)

    for it in plan:
        if it[0] == "divider":
            build_divider_slide(prs, it[1], it[2])
        else:
            _, title, entries, footer = it
            build_grid_slide(prs, title, entries, footer)

    if OUTPUT_PATH.exists():
        created = backup_presentation(str(OUTPUT_PATH),
                                      backup_base=str(OUTPUT_PATH.parent / "backups"))
        if created:
            print("\nBacked up previous deck.")
    prs.save(str(OUTPUT_PATH))
    print("\nDone. {} slides written to:\n  {}".format(
        len(prs.slides._sldIdLst), OUTPUT_PATH))
    if missing:
        print("Skipped {} missing panel(s).".format(len(missing)))


if __name__ == "__main__":
    main()
